# Generated by Django 3.0.1 on 2020-02-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.Subject'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='Tid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.TeacherInfo'),
        ),
    ]
