# Generated by Django 3.0.1 on 2020-02-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Question_Paper', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.TeacherInfo')),
                ('Subect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.StudentInfo')),
                ('Question_No', models.CharField(max_length=4)),
                ('Marks', models.IntegerField()),
                ('Checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TeacherInfo')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.StudentInfo')),
                ('Subect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.Subject')),
            ],
        ),
    ]
