# Generated by Django 3.0.1 on 2020-02-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Number_Of_Questions',
            field=models.IntegerField(default=0),
        ),
    ]
