# Generated by Django 3.0.1 on 2020-02-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200229_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaches',
            old_name='Subect',
            new_name='Subject',
        ),
    ]
